AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-backend-python

  Sample SAM Template for aws-backend-python

Parameters:
  PythonRuntime:
    Type: String

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: !Ref PythonRuntime
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
      SystemLogLevel: INFO

Resources:
  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jinja2/
      Handler: index.lambda_handler
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /
            Method: get
  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jinja2/
      Handler: search.lambda_handler
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: HttpApi
          Properties:
            Path: /search
            Method: get

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodeps/
      Handler: auth.lambda_handler
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: arn:aws:ssm:eu-central-1:796401245269:parameter/oauth2/orcid.org/0000-0003-2213-3552/APP-6KSLC9TDGOYVUOTT
      Events:
        Auth:
          Type: HttpApi
          Properties:
            Path: /auth
            Method: get

  CallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodeps/
      Handler: callback.lambda_handler
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: arn:aws:ssm:eu-central-1:796401245269:parameter/oauth2/orcid.org/0000-0003-2213-3552/APP-6KSLC9TDGOYVUOTT
      Events:
        Callback:
          Type: HttpApi
          Properties:
            Path: /callback
            Method: get

  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodeps/
      Handler: logout.lambda_handler
      Architectures:
        - x86_64
      Events:
        Logout:
          Type: HttpApi
          Properties:
            Path: /logout
            Method: get

Outputs:
  HelloWorldApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
