AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-backend-python

  Sample SAM Template for aws-backend-python

Parameters:
  PythonRuntime:
    Type: String

Globals:
  Function:
    Timeout: 3
    MemorySize: 128
    Runtime: !Ref PythonRuntime
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
      SystemLogLevel: INFO
    Environment:
      Variables:
        PMID_TABLE_NAME: !Ref PmidTablev3

Resources:
  PmidTablev3:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pmid
          AttributeType: S
      KeySchema:
        - AttributeName: pmid
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jinja2/
      Handler: handler.index.lambda_handler
      Architectures:
        - x86_64
      Events:
        E1:
          Type: HttpApi
          Properties:
            Path: /
            Method: get
  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jinja2/
      Handler: handler.search.lambda_handler
      Architectures:
        - x86_64
      Timeout: 900 # seconds (max 900)
      MemorySize: 1769 # MB (128–10240)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PmidTablev3
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: arn:aws:ssm:eu-central-1:796401245269:parameter/api-token/api.adsabs.harvard.edu/georgwendorf_gmail.com
      Events:
        E1:
          Type: HttpApi
          Properties:
            Path: /search
            Method: get
  DoiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jinja2/
      Handler: handler.doi.lambda_handler
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PmidTablev3
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: arn:aws:ssm:eu-central-1:796401245269:parameter/api-token/api.adsabs.harvard.edu/georgwendorf_gmail.com
      Events:
        E1:
          Type: HttpApi
          Properties:
            Path: /doi.org/{doi+}
            Method: get
  PmidFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jinja2/
      Handler: handler.pmid.lambda_handler
      Architectures:
        - x86_64
      Events:
        E1:
          Type: HttpApi
          Properties:
            Path: /pubmed.ncbi.nlm.nih.gov/{pmid}
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PmidTablev3
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: arn:aws:ssm:eu-central-1:796401245269:parameter/api-token/api.adsabs.harvard.edu/georgwendorf_gmail.com
  BibCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jinja2/
      Handler: handler.bibcode.lambda_handler
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PmidTablev3
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: arn:aws:ssm:eu-central-1:796401245269:parameter/api-token/api.adsabs.harvard.edu/georgwendorf_gmail.com
      Events:
        E1:
          Type: HttpApi
          Properties:
            Path: /ui.adsabs.harvard.edu/abs/{bibcode}
            Method: get
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodeps/
      Handler: auth.lambda_handler
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: arn:aws:ssm:eu-central-1:796401245269:parameter/oauth2/orcid.org/0000-0003-2213-3552/APP-6KSLC9TDGOYVUOTT
      Events:
        Auth:
          Type: HttpApi
          Properties:
            Path: /auth
            Method: get

  CallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodeps/
      Handler: callback.lambda_handler
      Architectures:
        - x86_64
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:GetParameter
              Resource: arn:aws:ssm:eu-central-1:796401245269:parameter/oauth2/orcid.org/0000-0003-2213-3552/APP-6KSLC9TDGOYVUOTT
      Events:
        Callback:
          Type: HttpApi
          Properties:
            Path: /callback
            Method: get

  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodeps/
      Handler: logout.lambda_handler
      Architectures:
        - x86_64
      Events:
        Logout:
          Type: HttpApi
          Properties:
            Path: /logout
            Method: get
  StreamProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodeps/
      Handler: dydb.lambda_handler
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt PmidTablev3.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
            Enabled: true

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
