AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  aws-backend-python

  Sample SAM Template for aws-backend-python

Parameters:
  PythonRuntime:
    Type: String

Globals:
  Function:
    Timeout: 30
    MemorySize: 128
    Runtime: !Ref PythonRuntime
    LoggingConfig:
      LogFormat: JSON
      ApplicationLogLevel: INFO
      SystemLogLevel: INFO
    Environment:
      Variables:
        PMID_TABLE_NAME: !Ref PmidTablev4
        SEARCH_CACHE_TABLE_NAME: !Ref SearchCache
        DOI2PMID_TABLE_NAME: !Ref Doi2Pmid
        DOI2ADS_TABLE_NAME: !Ref Doi2Ads
        DOI_CITS_TABLE_NAME: !Ref DoiCits
        PMID_LOOKUP_QUEUE_URL: !Ref PmidLookupQueue
        PMID_DOI_LOOKUP_QUEUE_URL: !Ref PmidDoiLookupQueue
        ADS_DOI_LOOKUP_QUEUE_URL: !Ref AdsDoiLookupQueue

Resources:
  PmidLookupQueue:
    Type: AWS::SQS::Queue
  PmidDoiLookupQueue:
    Type: AWS::SQS::Queue
  AdsDoiLookupQueue:
    Type: AWS::SQS::Queue
  PmidTablev4:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pmid
          AttributeType: S
      KeySchema:
        - AttributeName: pmid
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
  SearchCache:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: url
          AttributeType: S
      KeySchema:
        - AttributeName: url
          KeyType: HASH
  Doi2Pmid:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: doi
          AttributeType: S
      KeySchema:
        - AttributeName: doi
          KeyType: HASH
  DoiCits:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: doi
          AttributeType: S
      KeySchema:
        - AttributeName: doi
          KeyType: HASH
  Doi2Ads:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: doi
          AttributeType: S
      KeySchema:
        - AttributeName: doi
          KeyType: HASH
  CrossrefLastCrawl:
    Type: AWS::SSM::Parameter
    Properties:
      Name: !Sub "CrossrefLastCrawl-${AWS::StackName}"
      Type: String
      Value: "0"
  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jinja2/
      Handler: src.index.lambda_handler
      Architectures:
        - x86_64
      Events:
        E1:
          Type: HttpApi
          Properties:
            Path: /
            Method: get
  SearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jinja2/
      Handler: src.search.lambda_handler
      Architectures:
        - x86_64
      Timeout: 900 # seconds (max 900)
      MemorySize: 1769 # MB (128–10240)
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PmidTablev4
        - DynamoDBCrudPolicy:
            TableName: !Ref SearchCache
        - DynamoDBCrudPolicy:
            TableName: !Ref Doi2Pmid
        - DynamoDBCrudPolicy:
            TableName: !Ref Doi2Ads
        - SQSSendMessagePolicy:
            QueueName: !GetAtt PmidLookupQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt PmidDoiLookupQueue.QueueName
        - SQSSendMessagePolicy:
            QueueName: !GetAtt AdsDoiLookupQueue.QueueName
        - SSMParameterReadPolicy:
            ParameterName: api-token/api.adsabs.harvard.edu/georgwendorf_gmail.com
      Events:
        E1:
          Type: HttpApi
          Properties:
            Path: /search
            Method: get
  DoiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jinja2/
      Handler: src.doi.lambda_handler
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PmidTablev4
        - DynamoDBCrudPolicy:
            TableName: !Ref Doi2Ads
        - SSMParameterReadPolicy:
            ParameterName: api-token/api.adsabs.harvard.edu/georgwendorf_gmail.com
      Events:
        E1:
          Type: HttpApi
          Properties:
            Path: /doi.org/{doi+}
            Method: get
  PmidFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jinja2/
      Handler: src.pmid.lambda_handler
      Architectures:
        - x86_64
      Events:
        E1:
          Type: HttpApi
          Properties:
            Path: /pubmed.ncbi.nlm.nih.gov/{pmid}
            Method: get
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PmidTablev4
        - SSMParameterReadPolicy:
            ParameterName: api-token/api.adsabs.harvard.edu/georgwendorf_gmail.com
  BibCodeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: jinja2/
      Handler: src.bibcode.lambda_handler
      Architectures:
        - x86_64
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref PmidTablev4
        - SSMParameterReadPolicy:
            ParameterName: api-token/api.adsabs.harvard.edu/georgwendorf_gmail.com
      Events:
        E1:
          Type: HttpApi
          Properties:
            Path: /ui.adsabs.harvard.edu/abs/{bibcode}
            Method: get
  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodeps/
      Handler: src.auth.lambda_handler
      Architectures:
        - x86_64
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: oauth2/orcid.org/0000-0003-2213-3552/APP-6KSLC9TDGOYVUOTT
      Events:
        Auth:
          Type: HttpApi
          Properties:
            Path: /auth
            Method: get

  CallbackFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodeps/
      Handler: src.callback.lambda_handler
      Architectures:
        - x86_64
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: oauth2/orcid.org/0000-0003-2213-3552/APP-6KSLC9TDGOYVUOTT
      Events:
        Callback:
          Type: HttpApi
          Properties:
            Path: /callback
            Method: get

  LogoutFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodeps/
      Handler: src.logout.lambda_handler
      Architectures:
        - x86_64
      Events:
        Logout:
          Type: HttpApi
          Properties:
            Path: /logout
            Method: get
  StreamProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodeps/
      Handler: src.dydb.lambda_handler
      Events:
        DynamoDBStream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt PmidTablev4.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
            Enabled: true
  DoiCitsCrawler:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: nodeps/
      Handler: src.crossref.lambda_handler
      Environment:
        Variables:
          CROSSREF_LAST_CRAWL_PARAM: !Sub "CrossrefLastCrawl-${AWS::StackName}"
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - ssm:PutParameter
              Resource: !Sub arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/CrossrefLastCrawl-${AWS::StackName}
        - DynamoDBCrudPolicy:
            TableName: !Ref DoiCits

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
