---
on:
  push:
    branches:
      - main
  pull_request:

permissions: {}

jobs:
  deploy:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      id-token: write
    env:
      SAM_CLI_TELEMETRY: 0
      STACK_NAME: ${{ format('{0}-pr-{1}', github.event.repository.name, github.event_name == 'push' && github.ref_name || github.event.number) }}
    steps:
      - uses: actions/checkout@v6.0.1
      - uses: actions/setup-python@v6.1.0
      - uses: astral-sh/setup-uv@v7.1.6
        with:
          version: "0.9.21"
      - run: uv export --no-default-groups --frozen --directory jinja2 --output-file requirements.txt
      - uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          aws-region: eu-central-1
          role-to-assume: arn:aws:iam::796401245269:role/github
      - run: >
          sam build
          --parallel
          --parameter-overrides
          PythonRuntime="python$(cat .python-version)"
      - run: >
          sam deploy
          --stack-name "$STACK_NAME"
          --no-confirm-changeset
          --no-fail-on-empty-changeset
          --s3-bucket samclisourcebucket-d9da8a7d-03a2-496d-98b1-fff5081ccea1
          --s3-prefix "$STACK_NAME"/"$GITHUB_SHA"
          --capabilities CAPABILITY_IAM
          --parameter-overrides
          PythonRuntime="python$(cat .python-version)"
      - run: >
          echo url="$(
          sam list stack-outputs
          --stack-name "$STACK_NAME"
          --output json
          | jq -r '.[] | select(.OutputKey == "ApiUrl") | .OutputValue'
          )" >> "$GITHUB_ENV"
      - if: github.event_name == 'pull_request'
        run: gh pr comment ${{ github.event.number }} --edit-last --create-if-none --body "$url"
        env:
          GH_TOKEN: ${{ github.token }}
